import Head from 'next/head'
import { Box, Button, Container, Drawer, Paper, Stack, Typography } from '@mui/material'
import { useState } from 'react';
import Layout from '@/components/Layout';
import Footer from '@/components/Footer';
import ToggleTheme from '@/components/ToggleDark';
import { useDispatch, useSelector } from 'react-redux';
import { setLoaded } from '@/redux/homepageAction';
import Resistor1 from '@/components/Resistors/resistor1';
import Resistor from '@/components/Resistors/resistor';
import Resistor2 from '@/components/Resistors/resistor2';
import Resistors from '@/components/Resistors/resistor1';
import Resistor4 from '@/components/Resistors/resistor4';
import Resistor3 from '@/components/Resistors/resistor3';

const ResistorMenuBtns = [
  {
      title: "3 Band Resistor",
  },
  {
      title: "4 Band Resistor",
  },
  {
      title: "5 Band Resistor",
  },
  {
      title: "6 Band Resistor",
  },
]

const Page = (props) => {
  const loaded = useSelector(store=>store.homepage?.loaded)
  const resistorIndex = useSelector(store=>store.homepage?.resistorIndex)
  const dispatch = useDispatch()
  const resistorType = ResistorMenuBtns[resistorIndex]?.title
  const [resistorValues, setResistorValues] = useState({
    resistance: 0,
    tolerance: 0
  })

  const resetValues = () => {
    setResistorValues({
      resistance: 0,
      tolerance: 0
    })
  }

  const handleClick = async() => {
    const title = document.querySelector('.welcome_page')
    title.classList.add("remove")
    setTimeout(()=>{
      dispatch(setLoaded(true))
    }, [2000])
  }
  return (
    <>
      <Head>
        <title>Resistor Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Box
          sx={{
            height: "100vh",
            width: "100%",
            // bgcolor: "primary.contrastText",
            zIndex: "99",
            display: "flex",
            justifyContent: "center",
            // alignItems: "center"
          }}
        >
          <Stack gap={3}
            sx={{
              paddingTop: "5rem"
            }}
          >
            <Typography variant="h1"
              sx={{
                textAlign: "center",
                fontSize: {md: "3rem", xs: "2rem"},
              }}
            >{resistorType}</Typography>
            <Typography
              sx={{
                textAlign: "center",
              }}  
            >Click the color band to select color</Typography>
            <Box
              sx={{
                height: "fit-content",
                // bgcolor: "#000",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                position: "relative",
              }}
            >
              {
                resistorIndex == 0 ? (
                <Resistor1
                    height={{md: "25px", xs: "20px"}} 
                    width={{md: "550px", xs: "450px"}}
                />
                ) :
                resistorIndex == 1 ? (
                  <Resistor2
                      height={{md: "25px", xs: "20px"}} 
                      width={{md: "550px", xs: "450px"}}
                  />  
                ) :
                resistorIndex == 2 ? (
                  <Resistor3
                      height={{md: "25px", xs: "20px"}} 
                      width={{md: "550px", xs: "450px"}}
                  />  
                ) :
                (
                  <Resistor4
                      height={{md: "25px", xs: "20px"}} 
                      width={{md: "550px", xs: "450px"}}
                  />  
                )     
              }
            </Box>
          </Stack>
        </Box>
        <Box 
        sx={{
          position: "absolute",
          height: "100vh",
          width: "100%",
          bgcolor: "#000",
          display: loaded ? "none" : "flex",
          alignItems: "center",
          justifyContent: "center",
          top: "0",
          zIndex: "999"
        }}
        className="welcome_page"
        >
          <Container>
            <Stack gap={7} alignItems="center">
              <Typography
                variant="h1"
                sx={{
                  color: "#fff",
                  textAlign: "center",
                  fontSize: {md: "4rem", xs: "2rem"},
                  fontWeight: "900"
                }}
              >
                Welcome to Resistor Website</Typography>
                  <Box
                    sx={{
                      position: "relative",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center"
                    }}
                    className="resistor_container"
                  >
                    <Resistor height={{md: "25px", xs: "20px"}} 
                  width={{md: "550px", xs: "400px"}}  />
                    {/* <Resistor1 /> */}
                    {/* <Resistor1 /> */}
                    <Button
                        // color="gray"
                        sx={{
                            position: "absolute",
                            width: "100%",
                            height: "100%",
                            color: "#fff",
                            fontWeight: "bold",
                            zIndex: "10",
                            fontSize: {md: "1.5rem", xs: "1rem"},
                            zIndex: "9",
                            padding: "3rem"
                        }}
                        onClick={()=>handleClick()}
                        >
                            GET STARTED
                      </Button>
                  </Box>
            </Stack>
          </Container>
        </Box>
        <Footer ResistorMenuBtns={ResistorMenuBtns} />
    </>
  )
}

Page.getLayout = (page) => (
  <Layout>
    {page}
  </Layout>
);

export default Page
