import Head from 'next/head'
import { Box, Button, Container, Stack, Typography } from '@mui/material'
import Resistor from '@/components/resistor';

export default function Home() {
  return (
    <>
      <Head>
        <title>Resistor Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box 
      sx={{
        height: "100vh",
        width: "100%",
        bgcolor: "#000",
        display: "flex",
        alignItems: "center",
        justifyContent: "center"
      }}
      >
        <Container>
          <Stack gap={7} alignItems="center">
            <Typography
            variant="h1"
              sx={{
                color: "#fff",
                textAlign: "center",
                fontSize: {md: "4rem", xs: "2rem"},
              }}
              
            >
              Welcome to Resistor Website</Typography>
                <Box
                  sx={{
                    position: "relative",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center"
                  }}
                  className="resistor_container"
                >
                  <Resistor height={{md: "15px", xs: "10px"}} width={{md: "400px", xs: "300px"}} />
                  <Button
                      color="gray"
                      sx={{
                          position: "absolute",
                          width: "100%",
                          height: "100%",
                          color: "#fff",
                          fontWeight: "bold",
                          zIndex: "10",
                          fontSize: {md: "1rem", xs: "0.8rem"}
                      }}
                      >
                          GET STARTED
                    </Button>
                </Box>
          </Stack>
        </Container>
      </Box>
    </>
  )
}
